### ISSUE TITLE
No fetched Calendars in Android 13

### ISSUE THREAD

**Issue by krillin666** [ekalin/kalendar#1]
Hey @ekalin, congratulations on this widget, it's super useful.
Unfortunately, it has stopped working on Android 13. When you have time, could you look at it ?

Thank you for your time !

**Comment by ekalin** [comment]
That's strange, I did not find any change in Android 13 that should affect fetching calendars.

Nevertheless, I'll investigate it.

**Comment by krillin666** [comment]
Thanks ! The only other information I can give, that might be beneficial, is that the Calendar's are Caldav one's probably fetched from the DAVx5 app (?), they are all turned on in the Kalendar app's setting but nothing is displayed in the widget. Besides that, I'm using Calyx OS

**Comment by ekalin** [comment]
I've tested the app on Android 13 and it worked normally.

The calendars and events are fetched from the Android calendar service, and apps (such as DAVx5) can add calendars to this service. If you can see the calendars then it seems the calendars are being registered, but I don't have any idea why the events don't show up.

What you can try, if you haven't already, is to unselect and re-select the calendars, check the number of days to search for events, remove and re-add the widget. You could also see if the events are shown in another calendar app.
